### ISSUE TITLE
Trying it out

### ISSUE THREAD

**Issue by nzfarmer1** [nlkluth/mini-gauge#1]
Interesting work!

Are you able to please update your README on how to configure and run this demo?

I needed to replace .. with bower_components, but even after that I was just getting:

Uncaught TypeError: prototype.registerCallback is not a function

This was in Chrome (OSX) and Polymer 0.9

**Comment by nlkluth** [comment]
Thanks for taking a look. I haven't worked on this for awhile, so I am sure it is pretty out of date. I made some quick changes to the readme. Let me know if it works for you.
